cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add/', views.cart_add, name="cart_add"),
    path('<int:product_id>/<int:size_old>/update/', views.update_cart, name="update_cart"),
    path('<int:product_id>/<int:size>/remove/', views.cart_remove, name="cart_remove"),
    path('<int:product_id>/<int:size>/ajax/remove/', views.ajax_cart_remove, name="ajax_cart_remove"),

]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
	path('apply/',views.coupon_apply, name='coupon_apply'),
	path('manage/', views.coupon_manage, name='coupon_manage'),
	path('add/coupon/', views.coupon_add, name="coupon_add"),
	path('add/ajax/coupon/', views.ajax_add_coupons, name="ajax_add_coupons"),
	path('<int:coupon_id>/ajax/delete/', views.coupon_delete, name='coupon_delete'),
	path('<int:coupon_id>/ajax/update/', views.coupon_update, name='coupon_update'),
	path('ajax/delte/all/', views.coupon_delete_all, name='coupon_delete_all'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls",namespace="shop")),
    path("cart/", include("cart.urls")),
    path('orders/',include('orders.urls')),
    path("coupons/", include("coupons.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	path('checkout/', views.order_create, name='checkout'),
	path('ajax/<int:order_id>/paid/update/', views.change_status_paid, name='change_status_paid'),
	path('ajax/<int:order_id>/update/', views.order_update, name='order_update'),
	path('manage/', views.manage_orders , name='manage_orders'),
	path('detail/<int:order_id>/', views.order_detail, name='order_detail'),
	path('ajax/<int:order_id>/delete/', views.order_delete, name='order_delete'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path("<int:product_id>/ajax/delete-product/",views.delete_product, name="delete_product"),
	path("<int:product_id>/ajax/delete-image/",views.delete_image, name="delete_image"),
	path("<int:product_id>/upadte-product/",views.upadte_product, name="upadte_product"),
	path("<int:product_id>/ajax/update-product/",views.ajax_update_product, name="ajax_update_product"),
	path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
	path("upload/", views.upload_product, name="upload_product"),
	path("ajax/upload-product/", views.ajax_upload_product, name="ajax_upload_product"),
	path("ajax/check/name-product/", views.check_name_product, name="check_name_product"),
	path("manage/", views.manage_shop, name='manage_shop'),
	path("", views.home, name='home'),
	path("about/", views.about, name='about'),
	path("contact/", views.contact, name='contact'),
    path("list/", views.product_list, name="product_list"),
    path("<str:slug>/", views.product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from shop.models import SIZE_CHOICES


PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(
		choices=PRODUCT_QUANTITY_CHOICES,
		initial=1,
		coerce=int, label='SL'
	)
	size = forms.TypedChoiceField(
		choices= SIZE_CHOICES,
		initial=36,
		coerce=int
	)
	update_quantity = forms.BooleanField(
		required=False,
		initial=False,
		widget=forms.HiddenInput
	)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.admin.views.decorators import staff_member_required
from shop.models import Product
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product,id=product_id)
	form  = CartAddProductForm(request.POST)

	if form.is_valid():
		cd = form.cleaned_data

		cart.add(
			product=product,
			quantity=cd['quantity'],
			size=cd['size'],
			update_quantity=cd['update_quantity']
		)
	return redirect('cart:cart_detail')

def update_cart(request, product_id, size_old):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form  = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.update(
			product = product,
			quantity = cd['quantity'],
			size_old = size_old,
			size_new = cd['size'],
		)		

	return redirect('cart:cart_detail')

def cart_remove(request, product_id, size):
	cart = Cart(request)
	product  = get_object_or_404(Product, id=product_id)
	cart.remove(product,size)

	return redirect('cart:cart_detail')

def ajax_cart_remove(request, product_id, size):
	data ={}
	cart = Cart(request)
	product  = get_object_or_404(Product, id=product_id)

	cart.remove(product,size)

	data['total_item'] =  len(cart)
	data['total_price'] = cart.get_total_price()

	return JsonResponse(data)

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(
			initial= {
				'quantity': item['quantity'],
				'size': item['size'],
				'update_quantity': True
			}
		)

	coupon_apply_form = CouponApplyForm()

	return render(request,'cart/cart_detail.html',{'section':'shop','cart':cart, 'coupon_apply_form':coupon_apply_form})

templates/cart/cart_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}
	Giỏ hàng của tôi
{% endblock title %}

{% block content %}
	<main class="site-main">

		<section class="section table-cart">
			<div class="container">
				{% if message %}
				<div class="alert alert-dismissible alert-success">
					<i class="fa fa-check" aria-hidden="true"></i>
					<strong>Cập nhật thành công</strong>
				</div>
				{% endif %}
				<div class="table-responsive">
					<table class="table table-hover table_cart">
						<thead>
							<tr>
								<td scope="col">Ảnh</td>
								<td scope="col">Tên</td>
								<td>Giá</td>
								<td>Size</td>
								<td>Số lượng</td>
								<td>Tổng</td>
								<td>Cập nhật</td>
								<td>Xóa</td>
							</tr>
						</thead>
						<tbody>
							{% for item in cart  %}
								{% with product=item.product %}
								<tr>
									<form method="post" action="{% url 'cart:update_cart' product.id item.size %}">
										{% csrf_token %}
									<td><a class="cart-image" href="{% url "shop:product_detail" product.slug %}"><img width="78" height="107" src="{{product.photos.first.file.url}}" alt=""></a></td>

									<td><a href="{% url "shop:product_detail" product.slug %}" class="fz-16">{{product.name}}</a></td>

									<td><span class="br-product__price">{{product.price|intcomma}} vnđ</span></td>
									<td>
										<span class="ui-spinner ui-widget ui-widget-content ui-corner-all">
											{{item.update_quantity_form.size}}
										</span>
									</td>
									<td>
										<span class="ui-spinner ui-widget ui-widget-content ui-corner-all">
											{{item.update_quantity_form.quantity}}
										</span>
									</td>
									{{item.update_quantity_form.update_quantity}}

									<td><span class="br-product__price">{{item.total_price|intcomma}} vnđ</span></td>
									<td>
										<input type="submit" value="cập nhật" class="btn">
									</td>
						
									<td><a class="red close" href="{% url "cart:cart_remove" product.id item.size %}"><i class="fa fa-times" aria-hidden="true"></i></a></td>
									</form>
								</tr>
								{% endwith %}
							{% endfor %}

						</tbody>
					</table>
				</div>
				
				<div class="row">
					<div class="col-md-6 pb-40">
						<div class="alert alert-dark">
							<p>Nếu có mã giảm giá hãy nhập phía dưới</p>
						</div>

						<form class="js-coupon"  data-href="{% url "coupons:coupon_apply" %}" method="post" novalidate>
							{% csrf_token %}
							<div class="form-group">
								<label class="control-label">Mã</label>
								<div class="input-group">
									{% render_field coupon_apply_form.code %}
									<span class="input-group-btn"><button name="ACTION" value="COUPON" class="btn btn-default" type="submit">Áp dụng</button></span>
								</div>
								<span id="msg">
									
								</span>
							</div>

						</form>
						<div class="cart-total mb-70">
							<table>
								<tbody>
									<tr class="cart-subtotal"><th>Được giảm:</th><td class="js-discount">- {{cart.get_discount|intcomma}} vnđ ( {{cart.coupon.discount}} %)</td></tr>
									<tr class="shipping"><th>Phí Ship:</th><td>Free Shipping</td></tr>
									<tr class="order-total"><th>Tổng thanh toán:</th><td class="js-total-price">{{cart.get_total_price|intcomma}} vnđ</td></tr>
									<tr class="order-total"><th>Tổng thanh toán áp dụng giảm giá:</th><td><strong><span class="amount js-total-price-discount">{{cart.get_total_price_after_discount|intcomma}} vnđ</span></strong></td></tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
		
				<div class="text-center">
					<h5 class="text-uppercase">Tổng</h5>
					<h2 class="total-price mb-25">{{cart.get_total_price_after_discount|intcomma}} vnđ</h2>
					<a href="{% url 'shop:product_list' %}" class="btn btn-lg btn-outline btn-default">Tiếp tục mua sắp</a>
					<a href="{% url "orders:checkout" %}" class="btn btn-lg btn-default">Đi tới thanh toán</a>
				</div>
			</div>
		</section>
	</main>

{% endblock content %}

{% block scripts %}
	<script>
		$(function(){

			function numberWithCommas(x) {
		    	return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
			};

			$('form.js-coupon').submit( function(){
				
				$.ajax({
					url: $('form.js-coupon').attr("data-href"),
					dataType:"json",
					type: 'post',
					data: $('form.js-coupon').serialize(),
					success: function(data){
						if (data.is_coupon){
							$('.js-discount').text("- "+numberWithCommas(data.discount)+" vnđ ( "+data.percent+"% )");
							$('.js-total-price').text(numberWithCommas(data.total_price)+" vnđ");
							$('.js-total-price-discount').text(numberWithCommas(data.total_price_after_discount)+" vnđ");
							$('.total-price').text(numberWithCommas(data.total_price_after_discount)+" vnđ");
							$('#msg').html('<small class="form-text text-muted empty" style="color:#0f921c;">Chúc mừng ! Đơn hàng của bạn đã được giảm '+data.percent+'% </small>')
						} else {
							$('#msg').html('<small class="form-text text-muted empty" style="color:#ff0505;">Mã giảm giá không đúng</small>');
							$('.js-discount').text("- 0 vnđ ( 0% )");
							$('.js-total-price').text(numberWithCommas(data.total_price)+" vnđ");
							$('.js-total-price-discount').text(numberWithCommas(data.total_price)+" vnđ");
							$('.total-price').text(numberWithCommas(data.total_price)+" vnđ");
						}

					}
				});

				return false;
			});
		});
	</script>
{% endblock scripts %}