cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add/', views.cart_add, name="cart_add"),
    path('<int:product_id>/<int:size_old>/update/', views.update_cart, name="update_cart"),
    path('<int:product_id>/<int:size>/remove/', views.cart_remove, name="cart_remove"),
    path('<int:product_id>/<int:size>/ajax/remove/', views.ajax_cart_remove, name="ajax_cart_remove"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls",namespace="shop")),
    path("cart/", include("cart.urls")),
    path('orders/',include('orders.urls')),
    path("coupons/", include("coupons.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path("<int:product_id>/ajax/delete-product/",views.delete_product, name="delete_product"),
	path("<int:product_id>/ajax/delete-image/",views.delete_image, name="delete_image"),
	path("<int:product_id>/upadte-product/",views.upadte_product, name="upadte_product"),
	path("<int:product_id>/ajax/update-product/",views.ajax_update_product, name="ajax_update_product"),
	path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
	path("upload/", views.upload_product, name="upload_product"),
	path("ajax/upload-product/", views.ajax_upload_product, name="ajax_upload_product"),
	path("ajax/check/name-product/", views.check_name_product, name="check_name_product"),
	path("manage/", views.manage_shop, name='manage_shop'),
	path("", views.home, name='home'),
	path("about/", views.about, name='about'),
	path("contact/", views.contact, name='contact'),
    path("list/", views.product_list, name="product_list"),
    path("<str:slug>/", views.product_detail, name="product_detail"),
]

templates/includes/footer.html
{% load static %}

<footer class="site-footer">

	<div class="br-site-info">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-sm-8">
					<div class="br-site-contact">
						<a href="{% url 'shop:about' %}">Giới thiệu</a>
						<a href="{% url 'shop:contact' %}">Liên hệ</a>
						<a href="#">RSS</a>
						<a href="#">Site Map</a></div>
				</div>
				
			</div>
		</div>
	</div>

</footer>

templates/includes/header.html
{% load static %}
{% load cart_tag %}
<header class="site-header">
	{% if section == 'home' %}
	<div class="br-promotion br-promotion hidden-xs">
		<div class="container">
			<div class="row">
				<div class="col-sm-10 col-xs-10"><span class="text-uppercase small">free shipping on orders over $125 withing the us</span> <a href="{% url "shop:product_list" %}" class="btn btn-outline btn-sm">shop now</a></div>
				<div class="col-sm-2 col-xs-2"><button type="button" class="close"><i class="fa fa-times" aria-hidden="true"></i></button></div>
			</div>
		</div>
	</div>
	{% endif %}

	<div class="br-board br-board--white hidden-xs">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-4">
					<span class="small">Chào mừng bạn đến với Lucas Shoes</span>
				</div>
				<div class="col-md-6 col-sm-4"><div class="text-center"><a href="{% url "shop:home" %}" class="br-logo"><img src="{% static "img/logo-lucas-1.png" %}" alt=""></a></div></div>
			</div>
		</div>
	</div>

	<nav class="awemenu-nav awemenu-fadeup awemenu-nav--white">
		<div class="container">
			<div class="awemenu-container">
				<div class="navbar-icons">
					<div class="dropdown dropdown-animation"><a href="shopping-cart.html" data-toggle="dropdown" role="button"><i class="fa fa-search" aria-hidden="true"></i></a><div class="dropdown-menu dropdown-search"><div class="form-search"><form action="../../../external.html?link=http://envato.megadrupal.com/html/brilliant/index.html"><label class="sr-only">search</label><input name="search" type="text" placeholder="Tìm kiếm sản phẩm..." value=""> <button type="button" class="sr-only"><i class="fa fa-search" aria-hidden="true"></i></button></form></div></div></div>

					<div class="dropdown-right">
						{% cart_header request=request %}

						<div class="dropdown dropdown-animation"><a href="account.html" data-toggle="dropdown" role="button"><i class="fa fa-user" aria-hidden="true"></i></a><div class="dropdown-menu dropdown-account"><span>Xin chào!</span><h5 class="text-uppercase mb-20">{{request.user.username}}</h5><div class="avatar mb-25"><a href="#"><img src="{% static "img-demo/avatars/avt-account.jpg" %}" alt=""></a></div><span>Account infomation</span> <a href="#" class="account-link">Đăng xuất</a></div></div>

					</div>
				</div>

				<div class="awemenu-logo"><a href="index-2.html"><img src="{% static "img/logo-lucas-1.png" %}" alt=""></a></div>

				<ul class="main-navigation awemenu">

					<li class="{% if section == "home" %}active{% endif %} awemenu-item"><a href="{% url "shop:home" %}">Trang chủ</a></li>
					<li class="{% if section == "shop" %}active{% endif %} awemenu-item"><a href="{% url "shop:product_list" %}">Mua sắm</a></li>
					<li class="{% if section == "blog" %}active{% endif %} awemenu-item"><a href="">Blog</a></li>
					<li class="{% if section == "about" %}active{% endif %} awemenu-item"><a href="{% url "shop:about" %}">Giới thiệu</a></li>
					<li class="{% if section == "contact" %}active{% endif %} awemenu-item"><a href="{% url "shop:contact" %}">Liên hệ</a></li>
					{% if request.user.is_staff %}
					<li class="{% if section == "manage" %}active{% endif %} awemenu-item"><a href="{% url "shop:manage_shop" %}">Dành cho quản lý</a></li>
					{% endif %}
					
				</ul>
			</div>
		</div>
	</nav>
</header>

templates/includes/photo_list.html
{% for photo in photos  %}
	<div class="col-4">
		<div class="card" style="width: 18rem;">
		  <img class="card-img-top" src="{{photo.file.url}}">
		</div>
	</div>
{% endfor %}