cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add/', views.cart_add, name="cart_add"),
    path('<int:product_id>/<int:size_old>/update/', views.update_cart, name="update_cart"),
    path('<int:product_id>/<int:size>/remove/', views.cart_remove, name="cart_remove"),
    path('<int:product_id>/<int:size>/ajax/remove/', views.ajax_cart_remove, name="ajax_cart_remove"),

]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
	path('apply/',views.coupon_apply, name='coupon_apply'),
	path('manage/', views.coupon_manage, name='coupon_manage'),
	path('add/coupon/', views.coupon_add, name="coupon_add"),
	path('add/ajax/coupon/', views.ajax_add_coupons, name="ajax_add_coupons"),
	path('<int:coupon_id>/ajax/delete/', views.coupon_delete, name='coupon_delete'),
	path('<int:coupon_id>/ajax/update/', views.coupon_update, name='coupon_update'),
	path('ajax/delte/all/', views.coupon_delete_all, name='coupon_delete_all'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls",namespace="shop")),
    path("cart/", include("cart.urls")),
    path('orders/',include('orders.urls')),
    path("coupons/", include("coupons.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	path('checkout/', views.order_create, name='checkout'),
	path('ajax/<int:order_id>/paid/update/', views.change_status_paid, name='change_status_paid'),
	path('ajax/<int:order_id>/update/', views.order_update, name='order_update'),
	path('manage/', views.manage_orders , name='manage_orders'),
	path('detail/<int:order_id>/', views.order_detail, name='order_detail'),
	path('ajax/<int:order_id>/delete/', views.order_delete, name='order_delete'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path("<int:product_id>/ajax/delete-product/",views.delete_product, name="delete_product"),
	path("<int:product_id>/ajax/delete-image/",views.delete_image, name="delete_image"),
	path("<int:product_id>/upadte-product/",views.upadte_product, name="upadte_product"),
	path("<int:product_id>/ajax/update-product/",views.ajax_update_product, name="ajax_update_product"),
	path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
	path("upload/", views.upload_product, name="upload_product"),
	path("ajax/upload-product/", views.ajax_upload_product, name="ajax_upload_product"),
	path("ajax/check/name-product/", views.check_name_product, name="check_name_product"),
	path("manage/", views.manage_shop, name='manage_shop'),
	path("", views.home, name='home'),
	path("about/", views.about, name='about'),
	path("contact/", views.contact, name='contact'),
    path("list/", views.product_list, name="product_list"),
    path("<str:slug>/", views.product_detail, name="product_detail"),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from multiselectfield import MultiSelectField



class Photo(models.Model):
	product = models.ForeignKey(to="Product",on_delete=models.CASCADE,related_name='photos')
	file = models.FileField(upload_to='products/')
	uploaded_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ("-uploaded_at",)

SIZE_CHOICES = [(i,str(i)) for i in range(36,46)]

class Product(models.Model):
	name = models.CharField(('Tên sản phẩm'),max_length=100)
	slug = models.SlugField(max_length=100,unique=True, blank=True)
	size = MultiSelectField(choices =SIZE_CHOICES)
	description = models.TextField(('Miêu tả'), blank=True)
	price = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('-created','name')
		index_together = (('id','slug'),)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug= slugify(self.name)
		super(Product,self).save(*args,**kwargs)

	

shop/forms.py
from django import forms 
from .models import Product, SIZE_CHOICES, Photo

class PhotoForm(forms.ModelForm):
	class Meta:
		model = Photo
		fields = ('file', )

class ProductFormCreate(forms.ModelForm):
	size = forms.MultipleChoiceField(choices=SIZE_CHOICES)
	
	class Meta:
		model = Product
		fields = ['name','size','description','price']

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.text import slugify
from django.views import View
from django.views.decorators.http import require_POST
from django.contrib.admin.views.decorators import staff_member_required
from cart.forms import CartAddProductForm
from .models import Product, Photo
from .forms import ProductFormCreate, PhotoForm

def home(request):
	return render(request, 'home.html', {'section':'home'})
		
def about(request):
	return render(request, 'about.html',{'section':'about'})

def contact(request):
	return render(request, 'contact.html',{'section':'contact'})
	
def product_list(request):
	cart_form = CartAddProductForm()
	products = Product.objects.all()

	return render(request,'shop/list.html', {'products':products,'section':'shop','cart_form':cart_form})


def product_detail(request, slug):
	cart_form = CartAddProductForm()
	product = get_object_or_404(Product, slug=slug)

	return render(request,'shop/detail.html', {'product':product,'section':'shop','cart_form':cart_form})

def cart_detail(request):
	return render(request,'shop/cart_detail.html',{'section':'shop'})

@staff_member_required
def manage_shop(request):
	return render(request, 'shop/manage_shop.html',{'section':'manage'})

@staff_member_required
def upload_product(request):
	form  = ProductFormCreate(initial={"size":["36","37","38","39","40","41",'42',"43","44","45"]})

	return render(request, "shop/upload_product.html", {'form':form,'section':'upload'})

@staff_member_required
@require_POST
def ajax_upload_product(request):
	data = {}
	if request.method == 'POST':
		form = ProductFormCreate(request.POST)
		if form.is_valid():
			form.save()
			data["is_error"] = False
		else:
			data["is_error"] = True
			data['pricve_msg_error'] = "Tối đa 10 chữ số và 3 chữ số sau dấu phẩy" if form['price'].errors else ""

	return JsonResponse(data)

@staff_member_required
@require_POST
def ajax_update_product(request, product_id):
	data = {}
	obj = get_object_or_404(Product, id=product_id)
	
	if request.method == 'POST':
		form = ProductFormCreate(request.POST,instance=obj)
		if form.is_valid():
			form.save()
			data["is_error"] = False
		else:
			data["is_error"] = True
			data['pricve_msg_error'] = "Tối đa 10 chữ số và 3 chữ số sau dấu phẩy" if form['price'].errors else ""

	return JsonResponse(data)

class BasicUploadView(View):
	def post(self, request):
		form = PhotoForm(self.request.POST, self.request.FILES)

		if form.is_valid():
			photo = form.save(commit=False)
			product = Product.objects.first()
			photo.product = product
			photo.save()
			photos= Product.objects.first().photos.all()

			photo_html = render_to_string('shop/includes/product_photos_create.html', {'product':product, 'request':request})
			data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url,'photo_html':photo_html}
		else:
			data = {'is_valid': False}

		return JsonResponse(data)

@staff_member_required
def check_name_product(request):
	data = {}
	name = request.GET.get("name")
	slug = slugify(name)
	data['is_error'] = Product.objects.filter(slug=slug).exists()
	data['msg'] = "<a href='/"+slug+"/'> tại đây</a>"

	return JsonResponse(data)

@staff_member_required
def delete_product(request, product_id):
	data= {}
	product = get_object_or_404(Product,pk=product_id)
	product.delete()
	products = Product.objects.all()
	data['product_table_list'] = render_to_string("shop/includes/product_table_list.html",{'products':products,'request':request})

	return JsonResponse(data)

@staff_member_required
def delete_image(request, product_id):
	data= {}
	product = get_object_or_404(Product,pk=product_id)
	if product.photos.exists():
		product.photos.first().delete()

	photo_html = render_to_string('shop/includes/product_photos_create.html', {'product':product, 'request':request, "section":"update"})
	data['photo_html'] = photo_html

	return JsonResponse(data)

@staff_member_required
def upadte_product(request, product_id):
	product = get_object_or_404(Product,pk=product_id)
	form = ProductFormCreate(instance = product)

	return render(request,'shop/update_product.html',{'product':product, 'form':form,"section":"update"})

templates/shop/detail.html
{% extends "base.html" %}
{% load static %}

{% load humanize %}

{% block title %}
	{{product.name}}
{% endblock title %}

{% block content %}
	<div class="page-title page-title--classic bg-11 mb-0"></div>

    <section class="section-detail pb-30">
    	<div class="container">
    		<div class="br-product br-product-detail br-product-slide-vertical mt--90">
    			<div class="row">
                    {% include "shop/includes/product_photos.html" %}

    			<div class="col-lg-6">
    				<div class="br-product-detail__container">
    					<div class="br-product-detail__main">
    						<h2 class="text-uppercase normal">{{product.name}}</h2>
    						<span id="product_price" class="br-product__price fz-16">{{product.price|intcomma}}</span> vnđ

    						<div class="br-product__description"><p>{{product.description}}</p></div>

    						<form method="post" action="{% url "cart:cart_add" product.id %}" class="mb-20" novalidate>
                                {% csrf_token %}

    							<div class="row">
    								<div class="col-xs-4">
                                        <label class="control-label">{{cart_form.size.label}}</label>
                                        {{cart_form.size}}
                                       
    								</div>
    								<div class="col-xs-3">
                                        <label class="control-label">{{cart_form.quantity.label}}</label>
                                        {{cart_form.quantity}}
                                    </div>
    							</div>

        						<div class="variation-price mb-20">
        							Tổng : <span id="total_price" price="{{product.price}}" class="br-product__price">{{product.price|intcomma}}</span> vnđ
        						</div>

        						<div class="br-product__action mb-15">
        							<div class="tb">
        								<div class="table-cell-center">
                                            <button type="submit" class="btn btn-default btn-cart"><i class="fa fa-shopping-bag"></i> <span>Thêm vào giỏ hàng</span></button>
                                        </div>
                                
        							</div>
        						</div>
                            </form>

    					</div>

    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</section>

<section class="pt-80 pb-60">
	<div class="container">
		<h2 class="br-title text-center">Có thể bạn cũng thích</h2>

		<div class="row js-new-arrivals br-slick-white">
			<div class="col-md-3"><div class="br-product br-product--grid"><div class="br-product__media"><div class="br-product__thumb"><a href="#"><img src="img-demo/products/33.jpg" alt=""></a></div><div class="br-product__label-wrapper"><span class="br-product__label new">NEW</span></div><div class="br-product__action"><div class="tb"><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="cart"><span class="sr-only">cart</span> <i class="fa fa-shopping-bag"></i></a></div><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="wish list"><span class="sr-only">wish list</span> <i class="fa fa-heart"></i></a></div><div class="table-cell-center"><a class="btn js-product-popup" href="product-popup.html" data-toggle="tooltip" data-placement="top" title="" data-original-title="quick view"><span class="sr-only">quick view</span> <i class="fa fa-eye"></i></a></div></div></div></div><div class="br-product__main"><h4 class="br-product__name"><a href="#">Glasses Dramos</a></h4><span class="br-product__price">$168.00</span></div></div></div>

			<div class="col-md-3"><div class="br-product br-product--grid"><div class="br-product__media"><div class="br-product__thumb"><a href="#"><img src="img-demo/products/34.jpg" alt=""></a></div><div class="br-product__label-wrapper"><span class="br-product__label hot">HOT</span></div><div class="br-product__action"><div class="tb"><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="cart"><span class="sr-only">cart</span> <i class="fa fa-shopping-bag"></i></a></div><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="wish list"><span class="sr-only">wish list</span> <i class="fa fa-heart"></i></a></div><div class="table-cell-center"><a class="btn js-product-popup" href="product-popup.html" data-toggle="tooltip" data-placement="top" title="" data-original-title="quick view"><span class="sr-only">quick view</span> <i class="fa fa-eye"></i></a></div></div></div></div><div class="br-product__main"><h4 class="br-product__name"><a href="#">Parker crossbody bag</a></h4><span class="br-product__price">$98.00</span></div></div></div>

			<div class="col-md-3"><div class="br-product br-product--grid"><div class="br-product__media"><div class="br-product__thumb"><a href="#"><img src="img-demo/products/35.jpg" alt=""></a></div><div class="br-product__label-wrapper"><span class="br-product__label sale">SALE</span></div><div class="br-product__action"><div class="tb"><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="cart"><span class="sr-only">cart</span> <i class="fa fa-shopping-bag"></i></a></div><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="wish list"><span class="sr-only">wish list</span> <i class="fa fa-heart"></i></a></div><div class="table-cell-center"><a class="btn js-product-popup" href="product-popup.html" data-toggle="tooltip" data-placement="top" title="" data-original-title="quick view"><span class="sr-only">quick view</span> <i class="fa fa-eye"></i></a></div></div></div></div><div class="br-product__main"><h4 class="br-product__name"><a href="#">Glasses Dramos</a></h4><span class="br-product__price">$49.50 <del>$60.00</del></span></div></div></div>

			<div class="col-md-3"><div class="br-product br-product--grid"><div class="br-product__media"><div class="br-product__thumb"><a href="#"><img src="img-demo/products/36.jpg" alt=""></a></div><div class="br-product__label-wrapper"><span class="br-product__label popular">POPULAR</span> <span class="br-product__label hot">HOT</span></div><div class="br-product__action"><div class="tb"><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="cart"><span class="sr-only">cart</span> <i class="fa fa-shopping-bag"></i></a></div><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="wish list"><span class="sr-only">wish list</span> <i class="fa fa-heart"></i></a></div><div class="table-cell-center"><a class="btn js-product-popup" href="product-popup.html" data-toggle="tooltip" data-placement="top" title="" data-original-title="quick view"><span class="sr-only">quick view</span> <i class="fa fa-eye"></i></a></div></div></div></div><div class="br-product__main"><h4 class="br-product__name"><a href="#">Glasses Dramos</a></h4><span class="br-product__price">$32.000</span></div></div></div>

			<div class="col-md-3"><div class="br-product br-product--grid"><div class="br-product__media"><div class="br-product__thumb"><a href="#"><img src="img-demo/products/30.jpg" alt=""></a></div><div class="br-product__label-wrapper"><span class="br-product__label hot">HOT</span></div><div class="br-product__action"><div class="tb"><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="cart"><span class="sr-only">cart</span> <i class="fa fa-shopping-bag"></i></a></div><div class="table-cell-center"><a class="btn" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="wish list"><span class="sr-only">wish list</span> <i class="fa fa-heart"></i></a></div><div class="table-cell-center"><a class="btn js-product-popup" href="product-popup.html" data-toggle="tooltip" data-placement="top" title="" data-original-title="quick view"><span class="sr-only">quick view</span> <i class="fa fa-eye"></i></a></div></div></div></div><div class="br-product__main"><h4 class="br-product__name"><a href="#">Glasses Dramos</a></h4><span class="br-product__price">$32.00</span></div></div></div>
		</div>
	</div>
</section>

{% endblock content %}

{% block scripts %}
    <script src="{% static "js/shop/detail_product.js" %}"></script>
{% endblock scripts %}

templates/shop/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	Mua sắm - Locas Shoes
{% endblock title %}

{% block content %}
	<main class="site-main">
		<div class="page-title page-title--classic mb-0" style="background-image:url({% static "img-demo/bg-page-title/1.jpg" %})">
			<div class="container">
				<div class="page-title__main">
					<div class="row">
						<div class="col-md-6 col-sm-6"><h1 class="text-uppercase mb-5">Mua sắm</h1></div>
					</div>
				</div>
			</div>
		</div>
		<section>
			<div class="container">
				<div class="br-filter-wrapper">
					<div class="overflow-hidden">
						<div class="br-left">
							<a class="icon-filter" href="productslist-fullwidth.html"><span class="sr-only">Danh sách</span><i class="fa fa-th-list" aria-hidden="true"></i> </a>

							<a class="icon-filter active" href="productsgrid-fullwidth.html"><span class="sr-only">filter grid</span> <i class="fa fa-th" aria-hidden="true"></i> </a>

							<span class="ml-50">Showing 1-4 of 60 sản phẩm</span></div>

						<div class="br-right">
							<div class="br-filter-group br-filter-group--sort">
								<span>Sắp xếp theo</span>
								<select>
									<option>Phổ biến</option>
									<option>Xem nhiều</option>
									<option>Mới nhất</option>
									<option>Từ thấp tới cao</option>
									<option>Từ cao xuống thấp</option>
								</select>
							</div>

						</div>
					</div>
				</div>
			</div>

			<div class="container" id="product_table_list">
				{% include "shop/includes/product_table_list.html" %}
			</div>
		</section>
	</main>
{% endblock content %}
{% block scripts %}
	<script src="{% static "js/shop/list.js" %}"></script>
{% endblock scripts %}

templates/shop/manage_shop.html
{% extends "base.html" %}

{% block title %}
	Quản lý shop
{% endblock title %}

{% block content %}
<main class="site-typo">
    <div class="container">
    	<section class="section pb-40">
    		<h2 class="h1 text-uppercase text-center mb-25">Quản lý shop</h2>
    		<div class="br-heading">
    			<div class="row">
    				<div class="col-md-3">
    					<a href="{% url "shop:upload_product" %}" class="btn btn-success">Thêm sản phẩm </a>
    				</div>
    				<div class="col-md-3">
    					<a href="#" class="btn btn-info">Biểu đồ bán hàng</a>
    				</div>
    				<div class="col-md-3">
    					<a href="{% url 'orders:manage_orders' %}" class="btn btn-danger">Xem đơn đặt hàng</a>
    				</div>
    				<div class="col-md-3">
    					<a href="{% url 'coupons:coupon_manage' %}" class="btn btn-info">Cập nhật mã giảm giá</a>
    				</div>

    			</div>
    		</div>
    	</section>
</main>
{% endblock content %}

templates/shop/update_product.html
{% extends "base.html" %}
{% load static %}

{% load widget_tweaks %}

{% block title %}
	Thêm sản phẩm
{% endblock title %}

{% block content %}
<div class="page-title page-title--classic bg-11 mb-0"></div>

    <section class="section-detail pb-30">
    	<div class="container">
    		<div class="br-product br-product-detail br-product-slide-vertical mt--90">
    			<div class="row">
					<div id="js-photos">
						{% include "shop/includes/product_photos.html" %}
					</div>
    			<div id="show-content" class="col-lg-6">

					<div id="show-upload-image" class="form-group">
						<button data-href="{% url "shop:delete_image" product.pk %}" type="button" class="btn-danger btn btn-sm delete_image">
				          <span class="fa fa-trash-o"></span> Xóa ảnh này
				        </button>
						<button type="button" class="btn-primary btn  btn-sm js-upload-photos">
				          <span class="fa fa-cloud-upload"></span> Tải ảnh lên
				        </button>
						<input id="fileupload" type="file" name="file" multiple
						           style="display: none;"
						           data-url="{% url "shop:basic_upload" %}"
						           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
					</div>
    				<div style="display:none" id="show-msg-success">
						<div class="alert alert-dismissible alert-success">
							<i class="fa fa-check" aria-hidden="true"></i>
							<strong>Thành công</strong> Cập nhật sản phẩm thành công
						</div>
					</div>
					<div style="display:none" id="show-msg-error">
						<div class="alert alert-dismissible alert-danger">
							<i class="fa fa-times-circle" aria-hidden="true"></i>
							<strong>Lỗi</strong> Kiểm tra lại các trường nhập
						</div>
					</div>


					<form data-href="{% url "shop:ajax_update_product" product.pk %}" id="upload_product_form" method="post" novalidate>
						{% csrf_token %}
						<div class="form-group">
							{% render_field form.name placeholder="Tên sản phẩm" value=form.value class="form-control" data-href="/ajax/check/name-product/" %}
							<small id="ms_id_name" class="form-text text-muted" style="color:#ff0505;display:none">Bạn phải đặt tên cho sản phẩm</small>
				<!-- 			<small class="form-text text-muted" style="color:#ff0505">Sản phẩm này đã tồn tại</small> -->
						</div>
						<div class="row">
    						<div class="col-xs-12">
								<div class="form-group">
									{% render_field form.size class="form-control" %}
									{% if form.size.errors %}
									<small class="form-text text-muted" style="color:#ff0505">Giá không hợp lệ</small>
									{% endif %}
								</div>
							</div>
							<div class="col-xs-3">
								<div class="form-group">
									{% render_field form.price placeholder="Giá VND" class="form-control" %}
									<small id="ms_id_price" class="form-text text-muted" style="display:none;color:#ff0505">Giá trị không hợp lệ</small>
								</div>
							</div>
						</div>

						<div class="form-group">
							{% render_field form.description placeholder="Miêu tả" rows="5" class="form-control" %}
							<small id="ms_id_description" class="form-text text-muted" style="display:none;color:#ff0505">Hãy miêu tả gì đó về sản phẩm</small>
						</div>

						<div class="br-product__action mb-15">
							<div class="tb">
								<div class="table-cell-center">
									<button name="action" value="UPDATE" class="btn btn-default btn-cart js-submit">
										<span>Cập nhật</span>
									</button>
								</div>
							</div>
						</div>

					</form>
    			</div>
    		</div>
    	</div>
    </div>
</section>
{% endblock content %}

{% block scripts %}
<script>
	$(function(){
		$(".js-upload-photos").click(function () {
		$("#fileupload").click();
 	 });

	  $("#fileupload").fileupload({
	    url: $("#fileupload").attr('data-url'),
	    dataType: 'json',
	    done: function (e, data) {
	      if (data.result.is_valid) {
	        $('#js-photos').html(data.result.photo_html);
	      }
	    }
	  });
	});
</script>
<script src="{% static "js/shop/update_product.js" %}"></script>
{% endblock scripts %}

templates/shop/upload_product.html
{% extends "base.html" %}
{% load static %}

{% load widget_tweaks %}

{% block title %}
	Thêm sản phẩm
{% endblock title %}

{% block content %}
<div class="page-title page-title--classic bg-11 mb-0"></div>

    <section class="section-detail pb-30">
    	<div class="container">
    		<div class="br-product br-product-detail br-product-slide-vertical mt--90">
    			<div class="row">
					<div id="js-photos">
						{% include "shop/includes/product_photos_create.html" %}
					</div>

    			<div id="show-content" class="col-lg-6">

    				<div style="display:none" id="show-msg-success">
						<div class="alert alert-dismissible alert-success">
							<i class="fa fa-check" aria-hidden="true"></i>
							<strong>Thành công</strong> Hãy tải một số hình ảnh cho sản phẩm 
						</div>

						<div id="show-upload-image" class="form-group">
							<button type="button" class="btn-primary btn  btn-sm js-upload-photos">
					          <span class="fa fa-cloud-upload"></span> tải ảnh
					        </button>
							<input id="fileupload" type="file" name="file" multiple
							           style="display: none;"
							           data-url="{% url "shop:basic_upload" %}"
							           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
						</div>
					</div>

					<form disabled data-href="{% url "shop:ajax_upload_product" %}" id="upload_product_form" method="post" novalidate>
						{% csrf_token %}
						<div class="form-group">
							{% render_field form.name placeholder="Tên sản phẩm" class="form-control" data-href="/ajax/check/name-product/" %}
							<small id="ms_id_name" class="form-text text-muted" style="color:#ff0505;display:none">Bạn phải đặt tên cho sản phẩm</small>
				<!-- 			<small class="form-text text-muted" style="color:#ff0505">Sản phẩm này đã tồn tại</small> -->
						</div>
						<div class="row">
    						<div class="col-xs-12">
								<div class="form-group">
									{% render_field form.size class="form-control" %}
									{% if form.size.errors %}
									<small class="form-text text-muted" style="color:#ff0505">Giá không hợp lệ</small>
									{% endif %}
								</div>
							</div>
							<div class="col-xs-3">
								<div class="form-group">
									{% render_field form.price placeholder="Ngàn VND" class="form-control" %}
									<small id="ms_id_price" class="form-text text-muted" style="display:none;color:#ff0505">Giá trị không hợp lệ</small>
								</div>
							</div>
						</div>

						<div class="form-group">
							{% render_field form.description placeholder="Miêu tả" rows="5" class="form-control" %}
							<small id="ms_id_description" class="form-text text-muted" style="display:none;color:#ff0505">Hãy miêu tả gì đó về sản phẩm</small>
						</div>

						<div class="br-product__action mb-15">
							<div class="tb">
								<div class="table-cell-center">
									<button class="btn btn-default btn-cart js-submit">
										<span>Tạo sản phẩm</span>
									</button>
								</div>
							</div>
						</div>

					</form>
    			</div>
    		</div>
    	</div>
    </div>
</section>
{% endblock content %}

{% block scripts %}
<script>
	$(function(){
		$(".js-upload-photos").click(function () {
		$("#fileupload").click();
 	 });

	  $("#fileupload").fileupload({
	    url: $("#fileupload").attr('data-url'),
	    dataType: 'json',
	    done: function (e, data) {
	      if (data.result.is_valid) {
	        $('#js-photos').html(data.result.photo_html);
	      }
	    }
	  });
	});
</script>
<script src="{% static "js/shop/upload_product.js" %}"></script>
{% endblock scripts %}