cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add/', views.cart_add, name="cart_add"),
    path('<int:product_id>/<int:size_old>/update/', views.update_cart, name="update_cart"),
    path('<int:product_id>/<int:size>/remove/', views.cart_remove, name="cart_remove"),
    path('<int:product_id>/<int:size>/ajax/remove/', views.ajax_cart_remove, name="ajax_cart_remove"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("shop.urls",namespace="shop")),
    path("cart/", include("cart.urls")),
    path('orders/',include('orders.urls')),
    path("coupons/", include("coupons.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	path('checkout/', views.order_create, name='checkout'),
	path('ajax/<int:order_id>/paid/update/', views.change_status_paid, name='change_status_paid'),
	path('ajax/<int:order_id>/update/', views.order_update, name='order_update'),
	path('manage/', views.manage_orders , name='manage_orders'),
	path('detail/<int:order_id>/', views.order_detail, name='order_detail'),
	path('ajax/<int:order_id>/delete/', views.order_delete, name='order_delete'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
	path("<int:product_id>/ajax/delete-product/",views.delete_product, name="delete_product"),
	path("<int:product_id>/ajax/delete-image/",views.delete_image, name="delete_image"),
	path("<int:product_id>/upadte-product/",views.upadte_product, name="upadte_product"),
	path("<int:product_id>/ajax/update-product/",views.ajax_update_product, name="ajax_update_product"),
	path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
	path("upload/", views.upload_product, name="upload_product"),
	path("ajax/upload-product/", views.ajax_upload_product, name="ajax_upload_product"),
	path("ajax/check/name-product/", views.check_name_product, name="check_name_product"),
	path("manage/", views.manage_shop, name='manage_shop'),
	path("", views.home, name='home'),
	path("about/", views.about, name='about'),
	path("contact/", views.contact, name='contact'),
    path("list/", views.product_list, name="product_list"),
    path("<str:slug>/", views.product_detail, name="product_detail"),
]

orders/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon
from shop.models import Product

class Order(models.Model):
	first_name = models.CharField(verbose_name='Họ',max_length=50)
	last_name = models.CharField(verbose_name='Tên',max_length=50)
	email = models.EmailField()
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$')
	phone = models.CharField(validators=[phone_regex], max_length=12)
	address = models.CharField(verbose_name='Địa chỉ', max_length=250)
	city = models.CharField(max_length=100, verbose_name='Thành phố')
	note = models.TextField(blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)
	coupon = models.ForeignKey(Coupon, related_name='orders',null=True,blank=True,on_delete=models.CASCADE)
	discount = models.IntegerField(default=0, validators=[MinValueValidator(0),MaxValueValidator(100)]) 


	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return 'Đơn hàng của {} {}'.format(self.first_name, self.last_name)

	def get_total_cost(self):
		total_cost = sum(item.get_cost() for item in self.items.all())
		return int(total_cost - total_cost*(self.discount / 100))

	def get_full_name(self):
		return self.first_name +' ' +self.last_name


class OrderItem(models.Model):
	order = models.ForeignKey(Order,
							related_name='items',
							on_delete=models.CASCADE)

	product = models.ForeignKey(Product,
							related_name='order_items',
							on_delete=models.CASCADE)

	price = models.PositiveIntegerField()
	size = models.PositiveIntegerField()
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return f'{self.id}'

	def get_cost(self):
		return self.price*self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
	class Meta:
		model= Order
		fields = ['first_name','last_name','email','phone','address','city','note']

orders/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST
from cart.cart import Cart
from shop.models import Product
from coupons.forms import CouponApplyForm
from .models import Order, OrderItem
from .forms import OrderCreateForm

def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		data= {}

		form = OrderCreateForm(request.POST)
		if form.is_valid():
			data['error']=False
			order = form.save(commit=False)
			if cart.coupon:
				order.coupon = cart.coupon
				order.discount = cart.coupon.discount
			order.save()
			
			for item in cart:
				OrderItem.objects.create(order=order,
										product=item['product'],
										price=item['price'],
										size=item['size'],
										quantity=item['quantity'])
			cart.clear()
			request.session['coupon_id'] = None
			data['msg_success']= render_to_string("orders/checkout_complete.html")

		else:
			data['error']=True
			data['error_email'] = "Địa chỉ email không hợp lệ" if form['email'].errors else ""
			data['error_phone'] = "Số điện thoại không hợp lệ" if form['phone'].errors else ""

		return JsonResponse(data)

	else:
		form  = OrderCreateForm()


	return render(request, 'orders/checkout.html', {'form':form, 'cart':cart})

@staff_member_required
def manage_orders(request):
	orders = Order.objects.all()

	return render(request, 'orders/manage.html', {'orders':orders})

@staff_member_required
def order_detail(request,order_id):
	order = get_object_or_404(Order, id=order_id)
	form = OrderCreateForm(instance = order)

	return render(request, 'orders/order_detail.html',{'order':order,'form':form})

@staff_member_required
@require_POST
def order_update(request, order_id):
	data= {}
	order = get_object_or_404(Order, id=order_id)
	form = OrderCreateForm(request.POST, instance=order)
	if form.is_valid():
		form.save()
		data['error'] = False

	else:
		data['error']=True
		data['error_email'] = "Địa chỉ email không hợp lệ" if form['email'].errors else ""
		data['error_phone'] = "Số điện thoại không hợp lệ" if form['phone'].errors else ""

	return JsonResponse(data)

@staff_member_required
def order_delete(request, order_id):
	data = {}
	order = get_object_or_404(Order,id=order_id)
	order.delete()
	orders = Order.objects.all()
	data['tbody'] = render_to_string("orders/includes/orders_manage_tbody.html",{'orders':orders})

	return JsonResponse(data)

@staff_member_required
def change_status_paid(request,order_id):
	data = {}
	order= get_object_or_404(Order, id=order_id)
	order.paid = True if order.paid==False else False
	order.save()
	data['status'] = order.paid

	return JsonResponse(data)

templates/orders/checkout.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block title %}
	Thanh toán đơn hàng
{% endblock title %}

{% block content %}
	<main>
		<section class="section pb-60">
			<div class="container">
				{% if cart|length > 0 %}
					<!-- <div class="text-alert mb-40"><p>Returning customer? <a href="#" class="bold">Click here to login</a></p></div> -->
				<div class="row">
					<form id="js-checkout" data-href="{% url "orders:checkout" %}" method="post" novalidate>
						{% csrf_token %}
					<div class="col-md-6 pb-40">
						<div class="br-form-checkout">
								<h2 class="text-uppercase fz-30 mb-20">Thông tin nhận hàng</h2>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="{{form.first_name.id_for_label}}">{{form.first_name.label}}<sup>*</sup></label>
											{% render_field form.first_name class="form-control dark" placeholder="Họ" %}
											<span class="{{form.first_name.id_for_label}}"></span>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label for="{{form.last_name.id_for_label}}">{{form.last_name.label}}<sup>*</sup></label>
											{% render_field form.last_name class="form-control dark" placeholder="Tên" %}
											<span class="{{form.last_name.id_for_label}}"></span>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="{{form.address.id_for_label}}">{{form.address.label}}<sup>*</sup></label>
									{% render_field form.address class="form-control dark" placeholder="Địa chỉ" %}
									<span class="{{form.address.id_for_label}}"></span>
								</div>

								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="{{form.city.id_for_label}}">{{form.city.label}} <sup>*</sup></label>
											{% render_field form.city class="form-control dark" placeholder="Thành phố" %}
											<span class="{{form.city.id_for_label}}"></span>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="{{form.email.id_for_label}}">{{form.email.label}} <sup>*</sup></label>
											{% render_field form.email class="form-control dark" placeholder="Địa chỉ email" %}
											<span class="{{form.email.id_for_label}}"></span>
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label for="{{form.phone.id_for_label}}">{{form.phone.label}} <sup>*</sup></label>
											{% render_field form.phone class="form-control dark" placeholder="Số điện thoại" %}
											<span class="{{form.phone.id_for_label}}"></span>
										</div>
									</div>
								</div>

								<div class="form-group">
									<label for="{{form.note.id_for_label}}">{{form.note.label}}</label>
									{% render_field form.note rows="3" class="form-control dark" placeholder="Thông tin gì muốn shop cần lưu ý" %}
								</div>
						<!-- 		<label class="c-input c-checkbox dark"><input type="checkbox"> <span class="c-indicator"></span> Create an account?</label> -->

						</div>
					</div>

					<div class="col-md-5 col-md-offset-1 pb-40">
						<div class="payment-right">
							<h2 class="text-uppercase fz-30 mb-30">Đơn hàng chi tiết</h2>
							<div class="list-product-mini">
								<ul class="list-style-none">
									{% for item in cart  %}
									{% with  product=item.product  %}
									<li>
										<div class="product-mini">
											<a href="#" class="product-mini__img"><img src="{{product.photos.first.file.url}}" alt=""><span>{{item.quantity}}</span></a>
											<div class="product-mini__body">
												<h4 class="br-product__name"><a href="{% url "shop:product_detail" product.slug %}" tabindex="0">{{product.name}}</a></h4>
												<span class="br-product__price">{{product.price|intcomma}} vnđ x {{item.quantity}}</span>
												/ <span class="br-product__price">size : {{item.size}}</span>
												
											</div>
											<div class="product-mini__button">
												<a data-href="{% url "cart:ajax_cart_remove" product.id item.size %}" class="close js_remove_cart"><i class="fa fa-times" aria-hidden="true"></i></a>
											</div>
										</div>
									</li>
									{% endwith %}
									{% endfor %}

								</ul>

								<div class="total-product overflow-hidden mb-40">
									<h5 class="text-uppercase"><span class="pull-left">Tổng thanh toán:</span> <span class="pull-right total_price">{{cart.get_total_price|intcomma}} vnđ</span></h5>
									<br>
									{% if cart.coupon %}
										<h5 class="text-uppercase"><span class="pull-left">Giảm:</span> <span class="pull-right total_price">- {{cart.get_discount|intcomma}} vnđ ( {{cart.coupon.discount}} %)</span></h5>
										<br>
										<h5 class="text-uppercase"><span class="pull-left">Tổng thanh toán áp dụng giảm giá:</span> <span class="pull-right total_price">{{cart.get_total_price_after_discount|intcomma}} vnđ</span></h5>
								{% endif %}
								</div>

							</div>

							<h2 class="text-uppercase fz-30 mb-30">Phương thức thanh toán</h2>

							<div class="mb-40">
								<div class="br-checkbox mb-30">
									<div class="mb-15">
										<label class="c-input c-checkbox dark"><input id="truc_tiep" type="checkbox"> <span class="c-indicator"></span> Thanh toán trực tiếp</label>
									</div>
									<p style="display:none;" class="msg-truc-tiep">Sử dụng phương thức thanh toán trực tiếp nghĩa rằng bạn sẽ thanh toán sau khi nhận được hàng.
									<br>
									Trường hợp sản phẩm bị lỗi hoặc có bất cứ thắc mắc nào bạn có thể <a href="{% url 'shop:contact' %}">liên hệ</a> với Shop để được hỗ trợ.</p>
								</div>
								<div class="pb-20"><label class="c-input c-checkbox dark"><input type="checkbox"> <span class="c-indicator"></span> Credit Card</label></div>

								<ul class="list-payments list-inline">
									<li><a href="#" title=""><img src="img-demo/utils/american-express.png" alt=""></a></li>
									<li><a href="#" title=""><img src="img-demo/utils/mastercard.png" alt=""></a></li>
									<li><a href="#" title=""><img src="img-demo/utils/moneybookers.png" alt=""></a></li>
									<li><a href="#" title=""><img src="img-demo/utils/paypal.png" alt=""></a></li>
									<li><a href="#" title=""><img src="img-demo/utils/visa.png" alt=""></a></li>
									<li><a href="#" title=""><img src="img-demo/utils/2chekout.png" alt=""></a></li>
								</ul>
							</div>

							<div class="wc-proceed-to-checkout"><button type="submit" name="ACTION" value="CHECKOUT" class="btn btn-lg btn-primary">Thanh toán</button></div>
						</div>
					</div>
					</form>
				</div>
				{% else %}
				<div class="row">
					<div class="col-md-6 pb-40">
						<div class="br-form-checkout">
							<h2 class="text-uppercase fz-30 mb-20">Đơn đặt hàng trống!</h2>
						</div>
					</div>
				</div>
				{% endif %}
			</div>
		</section>
	</main>
{% endblock content %}

{% block scripts %}
	<script src="{% static "js/orders/checkout.js" %}"></script>
	<script>
	$(function(){
		function numberWithCommas(x) {
	    	return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
		}

		$('.js_remove_cart').click(function(){
			var $el = $(this);

			$.ajax({
				url: $(this).attr("data-href"),
				datType: 'json',
				type: 'get',
				success : function(data){
					$el.closest('li').remove();
					$('.total_price').text(numberWithCommas(data.total_price)+" VNĐ");
				}
			});
		});

		$('input:checkbox').change(function(){
			if ($('#truc_tiep').prop("checked")){
				$('.msg-truc-tiep').show();
			} else {
				$('.msg-truc-tiep').hide();
			}
		});

	});
	</script>
{% endblock scripts %}

templates/orders/checkout_complete.html
<section class="section pb-60">
	<div class="container">
		<div class="row">
			<div class="col-md-6 pb-40">
				<div class="br-form-checkout">
					<h2 class="text-uppercase fz-30 mb-20">Cảm ơn quý khách!</h2>
					<p>Đơn hàng của quý khách đã đặt thành công.</p>
				</div>
			</div>
		</div>
	</div>
</section>

templates/orders/manage.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
	Quản lý đơn đặt hàng
{% endblock title %}

{% block content %}
	<main class="site-main">
		<section class="section table-cart">
			<div class="container">
				<div class="row">

					<div class="col-lg-12">
						<div class="page-header">
							<h1>Có {{orders.count}} đơn đặt hàng</h1>
						</div>
						<div class="bs-component">

							<table class="table">
								<thead>
									<tr>
										<th scope="col">Họ và tên</th>
										<th scope="col">Địa chỉ</th>
										<th scope="col">Phone</th>
										<th scope="col">Ngày đặt</th>
		<!-- 								<th scope="col">Chi tiết đơn hàng</th>
		<th scope="col">Giảm giá</th>
		<th scope="col">Tổng</th> -->
										<th scope="col">Lưu ý</th>
										<th scope="col">Thanh toán</th>
										<th scope="col">Chi tiết</th>
										<th scope="col">Xóa</th>
									</tr>
								</thead>
								<tbody id="orders">
									{% include "orders/includes/orders_manage_tbody.html" %}
								</tbody>
							</table>

						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-xl-5">
						<a class="btn btn-success" id="create_coupon"><i class="fa fa-file-excel-o"></i> Xuất File Excel</a>
						<a class="btn btn-warning js_delte_all_item" data-href=""><i class="fa fa-file-pdf-o"></i> Xuất File pdf</a>
					</div>
				</div>

			</div>
		</section>
	</main>

{% endblock content %}

{% block scripts %}
	<script>
	$(function(){
		$('#orders').on('click','.js-delete', function(){
			var $el = $(this);

			$.ajax({
				url: $el.attr('data-href'),
				type: 'get',
				dataType:'json',
				success: function(data){
					$('#orders').html(data.tbody);
				}
			});

			return false;
		});
		$('#orders').on('click','#change_status_paid', function(){
			var $el = $(this);

			$.ajax({
				url: $el.attr('data-href'),
				dataType:'json',
				type: 'get',
				success: function(data){
					if (data.status){
						$el.html('<a href="" style="color:#21b53e"><i class="fa fa-check"></i></a>');
					} else {
						$el.html('<a href="" style="color:#b53b3b"><i class="fa fa-times"></i></a>');
					}
				}
			});

			return false;
		});
	});
	</script>
{% endblock scripts %}

templates/orders/order_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}
	Quản lý đơn hàng số {{order.id}}
{% endblock title %}

{% block content %}
	<main class="site-main">

		<section class="section table-cart">
			<div class="container">
				<div class="table-responsive">

					<table class="table table-hover table_cart">
						<thead>
							<tr>
								<td scope="col">Ảnh</td>
								<td scope="col">Tên</td>
								<td>Giá</td>
								<td>Size</td>
								<td>Số lượng</td>
								<td>Tổng</td>
							</tr>
						</thead>
						<tbody class="orders">
							{% include "orders/includes/orders_tbody.html" %}

						</tbody>
					</table>
				</div>
				
				<div class="row">
					<div class="col-md-6 pb-40">
						<div class="alert alert-dark">
							<p>Thông tin khách hàng</p>
						</div>
						<div style="display:none;" class="alert alert-dismissible alert-success">
							<i class="fa fa-check"></i>
							<strong>Cập nhật thành công</strong>
						</div>
						<div class="cart-total mb-70">
							<form id="js_order_form" data-href="{% url "orders:order_update" order.id %}" method="post" novalidate>
								{% csrf_token %}
								<table>
									<tbody>
										{% for field in form %}
											<tr>
												<th>{{field.label}}:</th>
												{% if field.label == "Note" %}
													<td>{% render_field field rows="3" %}<span class="{{field.id_for_label}}"></span></td>
												{% else %}
													<td>{% render_field field %}<span class="{{field.id_for_label}}"></span></td>
												{% endif %}
												
											</tr>
										{% endfor %}
										<tr><td><button type="submit" class="btn btn-default">Cập nhật</button></td></tr>
									</tbody>
								</table>
							</form>
						</div>
					</div>
					<div class="col-md-6 pb-40">
						<div class="alert alert-dark">
							<p>Thông tin đơn đặt hàng</p>
						</div>

						<div class="cart-total mb-70">
							<table>
								<tbody>
									{% if order.coupon %}
									<tr class="cart-subtotal">
										<th>Mã giảm giá:</th>
										<td>
											{{order.coupon.code}}
										</td>
									</tr>
									<tr class="cart-subtotal"><th>Được giảm:</th><td>- {{order.discount}} %</td></tr>
									{% endif %}
									<tr class="shipping"><th>Phí Ship:</th><td>Free Shipping</td></tr>
									<tr class="order-total">
										<th>
											{% if order.coupon %}
												Tổng thanh toán sau khi giảm giá
											{% else %}
												Tổng thanh toán
											{% endif %}
										</th>
										<td><strong><span class="amount">{{order.get_total_cost|intcomma}} vnđ</span></strong></td></tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
		
			</div>
		</section>
	</main>

{% endblock content %}

{% block scripts %}
	<script>
		$(function(){
			var check_empty = function(){
				$('small.empty').hide();
				var els = ['id_phone','id_address','id_city','id_email'];
				
				for (var el in els){
					var em = '#'+els[el]
					var error = '.'+els[el]
					if (!$(em).val()){
						$(error).html('<small class="form-text text-muted empty" style="color:#ff0505;">Trường này là bắt buộc</small>')
					} else {
						$(error).html('');
					}
				};
			};
			$('#js_order_form').on('submit', function(){
				var $form = $('#js_order_form');
				check_empty()
				$.ajax({
					url: $form.attr('data-href'),
					type: 'post',
					dataType:'json',
					data: $form.serialize(),
					success: function(data){
						if (data.error){
							if (!$('#id_email').val()) {
								$('.id_email').html('<small class="form-text text-muted empty" style="color:#ff0505;">Trường này là bắt buộc</small>')
							} else{
								$('.id_email').html('<small class="form-text text-muted empty" style="color:#ff0505;">'+data.error_email+'</small>');
							};
							if (!$('#id_phone').val()) {
								$('.id_phone').html('<small class="form-text text-muted empty" style="color:#ff0505;">Trường này là bắt buộc</small>')
							} else{
								$('.id_phone').html('<small class="form-text text-muted empty" style="color:#ff0505;">'+data.error_phone+'</small>');
							};

						} else {
							$('.alert-success').show().fadeOut(5000);
						}
					}
				});

				return false;
			});

		});
	</script>
{% endblock scripts %}